services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - xpack.watcher.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - socnet
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 || exit 1"]
      interval: 10s
      retries: 10

  logstash:
      image: docker.elastic.co/logstash/logstash:8.11.1
      container_name: logstash
      hostname: logstash
      environment:
        - LS_JAVA_OPTS=-Xms512m -Xmx512m
      volumes:
        - ./pipeline:/usr/share/logstash/pipeline
      ports:
        - "5044:5044"
        - "5000:5000"
        - "8080:8080"
      networks:
        - socnet

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
      - kibana_data:/usr/share/kibana/data
    ports:
      - "5602:5601"
    depends_on:
      - elasticsearch
    networks:
      - socnet

  filebeat:
    build: ./filebeat
    container_name: filebeat
    user: root
    volumes:
      - ./logs/server/syslog-client:/var/log/syslog-ng/syslog-client:rw
    depends_on:
      - logstash
    networks:
      - socnet

  shuffle-frontend:
    image: ghcr.io/shuffle/shuffle-frontend:nightly
    container_name: shuffle-frontend
    ports:
      - "3001:80"
    environment:
      - BACKEND_HOSTNAME=localhost
    networks:
      - socnet
    restart: always
    depends_on:
      - shuffle-backend

  shuffle-backend:
    image: ghcr.io/shuffle/shuffle-backend:nightly
    container_name: shuffle-backend
    ports:
      - "5001:5001"
    environment:
      - SHUFFLE_OPENSEARCH_URL=http://elasticsearch:9200
    networks:
      - socnet
    restart: always

  syslog-server:
    image: balabit/syslog-ng:latest
    container_name: syslog-server
    hostname: syslog-server
    ports:
      - "514:514/tcp"
    volumes:
      - ./logs/server:/var/log/syslog-ng
      - ./server/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
    networks:
      - socnet

  syslog-client:
    image: balabit/syslog-ng:latest
    container_name: syslog-client
    hostname: syslog-client
    depends_on:
      - syslog-server
    volumes:
      - ./client/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
    networks:
      - socnet

  elastalert:
    build: ./elastalert
    container_name: elastalert
    environment:
      - TZ=Europe/Madrid
    volumes:
      - ./elastalert/config:/opt/elastalert2/config
      - ./elastalert/rules:/opt/elastalert2/rules
    depends_on:
      elasticsearch:
        condition: service_healthy
      shuffle-backend:
        condition: service_started
    networks:
      - socnet
    restart: always
    
    
  opensearch:
    image: opensearchproject/opensearch:2.11.1
    container_name: shuffle-opensearch
    environment:
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin
      - bootstrap.memory_lock=true
      - cluster.name=shuffle-cluster
      - node.name=shuffle-opensearch
      - node.store.allow_mmap=false
      - DISABLE_PERFORMANCE_ANALYZER_AGENT_CLI=true
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - shuffle-database:/usr/share/opensearch/data:z
    ports:
      - "9201:9200"
    networks:
      - socnet
    restart: always

networks:
  socnet:
    driver: bridge

volumes:
  esdata:
  kibana_data:
  shuffle_data:
  shuffle-database:
