name: Failed Login Alert
type: frequency
index: "elastalert-logs-*"
num_events: 5
timeframe:
  minutes: 5
filter:
  - term:
      syslog_program.keyword: "sshd"
alert:
  - webhook
webhook:
  url: "http://shuffle:5000/api/v1/webhook/<workflow_id>"
  method: POST
  headers:
    Content-Type: application/json
